# DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-hibernate-onetoone
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: spring-hibernate-onetoone
server:
  port: 8080