server:
  port: 8080

# DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)

spring:
  application:
    name: spring-hibernate-onetoone
  datasource:
    url: jdbc:mysql://localhost:3306/spring-hibernate-onetoone
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

